parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     orthosonline
    database_user:     weborthos
    database_password: orthos102030

    mailer_transport: gmail
    mailer_host:       ~
    mailer_user:       mario.eugenio@gmail.com
    mailer_password:   mario@1985

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
