security:
    encoders:
        Core\OrthosBundle\Entity\Usuario: sha512


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Core\OrthosBundle\Entity\Usuario, property: sq_usuario }

    firewalls:
        secured_area:
            pattern: /.*
            logout: true
            security: true
            anonymous: true
            form_login:
               check_path: /login_check
               login_path: /login
               use_referer: true