<?php

namespace Core\DashboardBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DashboardController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\DashboardBundle\Controller\DashboardController();
        return $instance;
    }
}
