<?php

namespace Core\OrthosBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TabelaPrecoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Core\OrthosBundle\Controller\TabelaPrecoController();
        return $instance;
    }
}
