<?php

namespace Orthos\Bundle\MensagemBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MensagemController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\MensagemBundle\Controller\MensagemController();
        return $instance;
    }
}
