<?php

namespace Orthos\Bundle\FinanceiroBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LancamentosController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\FinanceiroBundle\Controller\LancamentosController();
        return $instance;
    }
}
