<?php

namespace Orthos\Bundle\AgendaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AgendaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\AgendaBundle\Controller\AgendaController();
        return $instance;
    }
}
