<?php

namespace Orthos\Bundle\ProntuarioBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProntuarioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\ProntuarioBundle\Controller\ProntuarioController();
        return $instance;
    }
}
