<?php

namespace Orthos\Bundle\ClinicaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClinicaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\ClinicaBundle\Controller\ClinicaController();
        return $instance;
    }
}
