<?php

namespace Orthos\Bundle\PacienteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PacienteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\PacienteBundle\Controller\PacienteController();
        return $instance;
    }
}
