<?php

namespace Orthos\Bundle\MediaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MediaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Orthos\Bundle\MediaBundle\Controller\MediaController();
        return $instance;
    }
}
